### ISSUE TITLE
How to visualize ERFs?

### ISSUE THREAD

**Issue by yinheyanxian** [gwenzhang/Voxel-Mamba#3]
Hello, thank you for your wonderful work!
I have reproduced your code and the results are very good. I really want to know how you visualize ERFs (effective receptive fields), and I also want to visualize them to observe more details

**Comment by Sctflash** [comment]
> Hello, thank you for your wonderful work! I have reproduced your code and the results are very good. I really want to know how you visualize ERFs (effective receptive fields), and I also want to visualize them to observe more details

Hi. Sorry to bother you. Can you share your CUDA version, python version, mamba-ssm and causal_conv1d version? I tried using the requirements.txt provided by the author, but it was not reproduced successfully. If you can share, thank you very much.

**Comment by gwenzhang** [comment]
Thank you for your attention. We will release the visualization codes after the nuScene codes.

**Comment by yinheyanxian** [comment]
> Thank you for your attention. We will release the visualization codes after the nuScene codes.

Thanks in advance. I'll be following your work.
