### ISSUE TITLE
The version of waymo dataset

### ISSUE THREAD

**Issue by xuanmingShang** [gwenzhang/Voxel-Mamba#4]
Which version of waymo dataset do you use for training?
![waymo](https://github.com/user-attachments/assets/423b0ceb-eccc-4aea-812e-92853aa1b59a)

**Comment by gwenzhang** [comment]
You can use any version of Waymo. The 3D object detection data is the same across different versions. By the way, I use the v1.4.0.

**Comment by gwenzhang** [comment]
You can use any version of Waymo. The 3D object detection data is the same across different versions.

**Comment by xuanmingShang** [comment]
okay, thank you very much!
