### ISSUE TITLE
About the scripts and the cfg_file

### ISSUE THREAD

**Issue by dwbzxc** [gwenzhang/Voxel-Mamba#6]
Hi! Congratulations on your great work! When reading your code, I find that the ```tools/scripts``` folder is missing. Could you provide the folder and the corresponding scripts mentioned in the README?

Meanwhile, could you tell me which config file did you use to train your network? Since there are so many config files in the ```cfgs``` folder, I'm not sure which one I should use.

Thanks a lot!

**Comment by gwenzhang** [comment]
Thanks for your advice. We have updated the script files and specified which configuration to use in the README.

**Comment by dwbzxc** [comment]
Great! Thanks for your quick reply!
